models/ze_last_battle/last_big_destructor.mdl
models/ze_last_battle/last_destructor.mdl
models/ze_last_battle/last_truck.mdl
sound/ze_last_battle/last_ambience.wav
sound/ze_last_battle/last_ambience_final.wav
sound/ze_last_battle/last_battle.wav
sound/ze_last_battle/last_coming.wav
sound/ze_last_battle/last_copy.wav
sound/ze_last_battle/last_final_battle.wav
sound/ze_last_battle/last_footstep.wav
sound/ze_last_battle/last_hydras.wav
sound/ze_last_battle/last_pain.wav
sound/ze_last_battle/last_victory.wav
sprites/ze_last_battle/last_exp.spr
sprites/ze_last_battle/spectre_way.spr
maps/ze_last_battle_b2.bsp
maps/ze_last_battle_b2.txt
maps/ze_last_battle_b2.res